// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kekmfsxfeqtaceloiyfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtla21mc3hmZXF0YWNlbG9peWZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTIwMjYsImV4cCI6MjA2NDAyODAyNn0.V_b7Rj-Qp0NYBxq148-5t37jh1iVAoR_r6CNk3KZag8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);